import openai

def ask_chatgpt(question_to_chatgpt: str) -> str:

    """
    Accesses the API of Chat GPT and returns the generated content 

    Arguments:
    question_to_chatgpt (str): the input question for chat gpt 

    Returns:
    generated_content (str): a string containing the content generated by chat gpt 
    """
    # Insert the key for Open AI 
    openai.api_key = "xxx"

    # Accesses the API of Chat GPT to ask the question_to_chatgpt generated earlier 
    response = openai.ChatCompletion.create(
        model="gpt-3.5-turbo",
        messages=[
            {"role": "system", "content": "You are an informative assistant."},
            {"role": "user", "content": question_to_chatgpt},
        ],
        temperature=0.7,
    )

    # Save and return the generated content
    generated_content = response['choices'][0]['message']['content']

    return str(generated_content.strip())

